frontend_page:
    path:     /{slug}
    defaults: { _controller: "SiteMainBundle:Frontend/Page:index", parent : null }

frontend_page_child:
    path:     /{parent}/{slug}
    defaults: { _controller: "SiteMainBundle:Frontend/Page:index" }
